apiVersion: v1
kind: Service
metadata:
  name: corp-app
  labels:
    app: corp-app
spec:
  clusterIP: None
  ports:
    - port: 50051
      name: corp-app
  selector:
    app: corp-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corp-app
  labels:
    app: corp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corp-app
  template:
    metadata:
      labels:
        app: corp-app
    spec:
      containers:
      - name: corp-app
        image: corp-app
        ports:
        - containerPort: 50051
          name: http
