apiVersion: apps/v1
kind: Deployment
metadata:
  name: incluster-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incluster-deployment
  template:
    metadata:
      labels:
        app: incluster-deployment
    spec:
      serviceAccountName: incluster-sa
      containers:
      - name: incluster-container
        image: ghcr.io/westleaf/incluster-deployment:latest
        ports:
        - containerPort: 8080
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: token
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: webhook-secret
              key: secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: incluster-service
spec:
  selector:
    app: incluster-deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incluster-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: incluster-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["core"]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: incluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: incluster-role
subjects:
- kind: ServiceAccount
  name: incluster-sa
  namespace: default
---
