name: Build Simple Server Image

on:
  push:
    branches:
      - main
    paths:
      - 'simple-server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'simple-server/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Run tests
        working-directory: examples/simple-server
        run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t simple-server simple-server

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/examples/simple-server
          push: true
          tags: ghcr.io/${{ github.repository }}/simple-server:${{ github.sha }}
